spring:
  rabbitmq:
    host: 192.168.47.100
    port: 11111
    username: hanson
    password: 123456
    virtual-host: /
    publisher-confirm-type: CORRELATED # 交换机的确认
    publisher-returns: true # 队列的确认
logging:
  level:
    com.hanson.mq.config.MQProducerAckConfig: info
