# 应用服务 WEB 访问端口
server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/your_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 6379
  cache:
    type: redis

mybatis:
  mapper-locations: classpath:mappers/*xml
  type-aliases-package: com.hanson.cache.mybatis.entity