# 应用服务 WEB 访问端口
server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://47.116.123.21:3306/test
    username: user
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 6379


mybatis:
  mapper-locations: classpath:mappers/*xml
  type-aliases-package: com.hanson.cache.mybatis.entity