spring:
  rabbitmq:
    host: 192.168.47.100
    port: 11111
    username: hanson
    password: 123456
    virtual-host: /
    listener:
      simple:
        acknowledge-mode: manual
logging:
  level:
    com.hanson.mq.listener.MyProcessor: info
